### PR TITLE
reCaptcha3 support for Mautic 2

### PR DESCRIPTION
**Pull request by kuzmany**
Support for reCaptcha3 with backward compatibility. 
Users can switch to reCaptcha from plugin settings

### CODE REVIEW

**Comment by KonstantinCodes** [comment]
Wow, that's incredible! Haven't had time to check it yet but code looks good!

**Comment by YosuCadilla** [comment]
Hi guys, does it work? Is it dangerous? (conflicting files)

**Comment by kuzmany** [comment]
@YosuCadilla I've build it for one client times ago for Mautic 2.
I've just made pull request. After resolve conflicts, should works.

**Comment by YosuCadilla** [comment]
@KonstantinCodes, since you don't have a lot of time to keep merging this PR, would it be OK if I fork the project and do so myself?

@kuzmany, it would also contain your code, if that is OK with you.

I'd name it mautic-recaptcha-v3. I'd the conflicts, (already did, was simple) and from there, I'd try to keep up to date with PRs and Issues...

A lot of people use this plug-in and it needs maintenance, and with Mautic 4, possibly some more development.

Please let me know...

**Comment by KonstantinCodes** [comment]
@kuzmany The only problem is the conflicting files, otherwise it can be merged.

**Comment by kuzmany** [comment]
Close.
Resolve conflicts bring another PR

**Pull request closed without merging**
